language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

sudo: required

# safelist
branches:
  only:
  - master
  - development

services:
  - docker

script:
  - docker build --tag oduwsdl/fch .
  - docker run oduwasl/fch

after_script:
  - docker images

before_deploy:
  - docker login -u "naumansiddiqui4" -p "Ronaldo#1989"

deploy:
  provider: script
  script: docker push oduwsdl/fch
  on:
    branch: development

